### ISSUE TITLE
Add `golangci-lint`

### ISSUE THREAD

**Issue by iamrajiv** [haifahrul/go-server-side-ag-grid#31]
## Description

`golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports `yaml` config, has integrations with all major IDE, and has dozens of linters included.

## References

https://golangci-lint.run/

**Comment by iamrajiv** [comment]
@haifahrul I want to work on this.

**Comment by haifahrul** [comment]
Hi @iamrajiv 

Sorry for late reply. My pleasure, I will assign that issue to you.

thank you
